//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Areas.Core.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Catalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_Catalog()
        {
            this.Enagement_Details = new HashSet<Enagement_Details>();
        }
    
        public int Client_Catalog_ID { get; set; }
        public string Client_Code { get; set; }
        public string Client_Name { get; set; }
        public string Client_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enagement_Details> Enagement_Details { get; set; }
    }
}
