//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Areas.Core.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporation_Catalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Corporation_Catalog()
        {
            this.Facility_Catalog_FK = new HashSet<Facility_Catalog>();
        }
    
        public string Corporation_Name { get; set; }
        public string Corporation_Description { get; set; }
        public string Industry { get; set; }
        public string Corporation_Type { get; set; }
        public string Date_of_Incorpration { get; set; }
        public string Fiscal_Year_Start { get; set; }
        public string Number_of_Employees { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Area_Code { get; set; }
        public string Phone_Number { get; set; }
        public string Extensions_Name { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Updated_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Corporation_Code { get; set; }
        public int Corporation_Catalog_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facility_Catalog> Facility_Catalog_FK { get; set; }
    }
}
