//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Areas.Core.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enagement_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enagement_Details()
        {
            this.Client_Catalog = new HashSet<Client_Catalog>();
        }
    
        public int Engagement_Details_ID { get; set; }
        public bool Engagement_Detail_Is_Active { get; set; }
        public System.DateTime Engagement_Start_Date { get; set; }
        public System.DateTime Engagement_End_Date { get; set; }
        public System.DateTime Engagement_Baseline_Start_Date { get; set; }
        public System.DateTime Engagement_Baseline_End_Date { get; set; }
        public string Engagement_Revenue { get; set; }
        public string Engagement_Expense { get; set; }
        public string Engagement_Profit { get; set; }
        public string Engagement_Revenue_Budget { get; set; }
        public string Engagement_Expense_Budget { get; set; }
        public string Engagement_Profit_Budget { get; set; }
        public int Engagement_Catalog_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Catalog> Client_Catalog { get; set; }
        public virtual Engagement_Catalog Engagement_Catalog { get; set; }
    }
}
