//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.Areas.Core.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility_Catalog
    {
        public int Facility_Catalog_ID { get; set; }
        public int Corporation_Catalog_ID { get; set; }
        public string Facility_Code { get; set; }
        public string Facility_Name { get; set; }
    
        public virtual Corporation_Catalog Corporation_Catalog_FK { get; set; }
    }
}
